language: php
php:
 - "5.5"
 - "5.3"

before_script: 
 - "rm -r vendor"
 - ./composer.phar install
script: 
 - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script:
 - ./vendor/bin/test-reporter